added restrict access
wolox-training/ai-rails pull request #13
Opened 2017-11-24 13:39 UTC by axeliglesias

# SUMMARY
Added restrict acces using Pundit

# TRELLO CARD
https://trello.com/c/v1PR1wEU

2017-11-24 17:42 UTC, icoluccio requested changes

2017-11-24 17:42 UTC, icoluccio commented on app/controllers/rents_controller.rb
> +  # TODO: si entran por user_id o por book_id es la misma url. Como identificarlo?
Comments should be in English.

About the comment: now the solution with just one method doesn't work anymore, so we should just split the method in 2

2017-11-27 17:49 UTC, axeliglesias commented
I made a mistake on rents_controller: the url is not the same. 
One is /books/:book_id/rents and the other /users/:user_id/rents
Then, I have to authorize the acces only for the users url.

2017-11-27 17:52 UTC, icoluccio approved these changes

2017-11-27 17:52 UTC, icoluccio commented on app/controllers/rents_controller.rb
> +      authorize Rent.includes(:user, :book).where(user_id: params[:user_id])
Since `Rent.includes(:user, :book).where(user_id: params[:user_id])` is repeated twice, extract it to a local variable

2017-11-27 18:05 UTC, merged